[package]
name = "leaf-create-react"
license = "GPL-3.0"
description = "A simple CLI tool to create a new React project"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed = "8.3.0"
